version: '3'

services:

  database:
    container_name: "database"
    image: "mysql:8.0.18"
    ports:
      - "3306:3306"
    networks:
      - "spendwisenet"
    volumes:
      - "spendwisedata:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=ZGF0YWJhc2VwYXNzd29yZAo="
      - "MYSQL_DATABASE=spendwise"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 3

  keycloak:
    container_name: "keycloak"
    image: "quay.io/keycloak/keycloak:20.0.0"
    command: "start-dev"
    environment:
      - "KC_DB=mysql"
      - "KC_DB_USERNAME=root"
      - "KC_DB_PASSWORD=ZGF0YWJhc2VwYXNzd29yZAo="
      - "KC_DB_URL_HOST=database"
      - "KC_DB_URL_DATABASE=spendwise"
      - "KC_DB_SCHEMA=spendwise"
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=VW00UzNOaEFGMHJUM1ByMEtFWUNsMDRrCg=="
    ports:
      - "8585:8080"
    networks:
      - "spendwisenet"
    depends_on:
      database:
        condition: "service_healthy"

  backend:
    container_name: "backend"
    image: "cristian486/spendwise"
    ports:
      - "8080:8080"
    networks:
      - "spendwisenet"
    environment:
      - "KEYCLOAK_URL=http://192.168.0.13:8585"
      - "ISSUER_URI=http://192.168.0.13:8585/realms/spendwise"
      - "JWK_URI=http://192.168.0.13:8585/realms/spendwise/protocol/openid-connect/certs"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      database:
        condition: "service_healthy"

volumes:
  spendwisedata:
    driver: 'local'

networks:
  spendwisenet:
    driver: 'bridge'