name: spendwise-master-workflow

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  application-build:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Fazendo checkout no branch

      - uses: actions/setup-java@v3
        name: Configurando Java na máquina
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executando Build com o Maven
        run: mvn clean test package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile
          context: .
          tags: cristian486/spendwise:latest

